### ISSUE TITLE
BioShock Infinite disc 1: default.xex not found

### ISSUE THREAD

**Issue by JohnVeness** [eliecharra/iso2god-cli#3]
With BioShock Infinite disc 1, I get the following error:
```
$ iso2god.exe DVD1.iso god/
Iso2god-cli v1.3.6 - Team Executer
Ported to CLI by Elie CHARRA <elie [dot] charra [at] gmail.com>
Usage : iso2god <source iso> <destination folder>

+ Computing ISO metadata ...
Unhandled Exception  for directory at sector 2106394 -> ArgRange_Array
Parameter name: byteCount

Unhandled Exception:
System.Exception: Could not locate default.xex.
  at Chilano.Iso2God.IsoDetails.IsoDetails_DoWork () [0x00000] in <filename unknown>:0
  at Chilano.Iso2God.Program.Main () [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Could not locate default.xex.
  at Chilano.Iso2God.IsoDetails.IsoDetails_DoWork () [0x00000] in <filename unknown>:0
  at Chilano.Iso2God.Program.Main () [0x00000] in <filename unknown>:0
```
If I extract the ISO, the default.xex file is present.

I'm not sure if this app is still being developed, but many thanks for it, and for making it open source.

**Comment by JohnVeness** [comment]
The iso converts ok in the GUI version of Iso2God 1.3.6 so the problem is something specific to this version.

**Comment by eliecharra** [comment]
Dupplicate of #4, this is actually the same tech glitch under the hoods

**Comment by eliecharra** [comment]
> I'm not sure if this app is still being developed, but many thanks for it, and for making it open source.

Your're welcome :wink: And no, I dont have time to maintain this code anymore, but feel free to investigate this issue and submit a MR :wink: But be careful to test other games images to avoid break any behavior :smiley:
